
coverage:
  precision: 2
  round: nearest
  range: "70...100"
  ignore:
    - mambaTests/**/*

  status:
    project:
      default:
        target: auto
        branches:
          - master
          - develop

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
  branches:
    - master
    - develop