clean: true
author: Comcast VIPER
author_url: https://stackoverflow.com/jobs/companies/comcast-viper
github_url: https://github.comcast.com/viper-player/mamba_ios
min_acl: internal
skip_undocumented: false
hide_documentation_coverage: false
source_directory: .
readme: README.md
theme: fullwidth
use_safe_filenames: true
copyright: "Copyright © 2017 Comcast Corporation under [Apache License 2.0](https://github.comcast.com/viper-player/mamba_ios/blob/develop/LICENSE)."
